apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:10.4.1
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: {{ .Values.grafana.adminUser }}
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.grafana.adminPassword }}
            - name: GF_SERVER_ROOT_URL
              value: "http://localhost:8080/grafana/"
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: "true"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: dashboards
              mountPath: /var/lib/grafana/dashboards
            - name: provisioning-dashboards
              mountPath: /etc/grafana/provisioning/dashboards
            - name: provisioning-datasources
              mountPath: /etc/grafana/provisioning/datasources
          resources:
{{ toYaml .Values.resources.grafana | indent 12 }}
      volumes:
        - name: dashboards
          configMap:
            name: {{ .Release.Name }}-grafana-dashboard
        - name: provisioning-dashboards
          configMap:
            name: {{ .Release.Name }}-grafana-provisioning-dashboards
        - name: provisioning-datasources
          configMap:
            name: {{ .Release.Name }}-grafana-provisioning-datasources